spring.application.name=payment-cheque
server.port=8080


# ===============================
# Spring actuator
# ===============================
management.endpoints.web.exposure.include=health,prometheus
# ===============================
# Logging
# ===============================
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=100ms,150ms,250ms,500ms,1s
management.metrics.enable.jvm=true

#logging
logging.level.org.zalando.logbook=TRACE
logbook.exclude=/actuator/*
spring.cloud.compatibility-verifier.enabled=false

# ===============================
# DB UNICUS
# ===============================
spring.datasource.unicus.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.unicus.url=jdbc:oracle:thin:@p260unc4.vesta.ru:1566:uncunc
spring.datasource.unicus.username=${UNICUS_DB_USERNAME}
spring.datasource.unicus.password=${UNICUS_DB_PASSWORD}
spring.datasource.unicus.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.unicus.hikari.maximum-pool-size=50
spring.datasource.unicus.hikari.minimum-idle=3

internet.contract.url=http://localhost:11004/internet-contract-payment