spring.application.name=payment-cheque
server.port=8080


# ===============================
# Spring actuator
# ===============================
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.shutdown.enabled=true
management.endpoint.health.show-details=always
# ===============================
# Logging
# ===============================
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=100ms,150ms,250ms,500ms,1s
management.metrics.enable.jvm=true

#logging
logging.level.org.zalando.logbook=TRACE
logbook.exclude=/actuator/*
spring.cloud.compatibility-verifier.enabled=false

# ===============================
# Spring actuator
# ===============================


internet.contract.url=http://localhost:11004/internet-contract-payment