--liquibase formatted sql

--changeset internet-contract:001-create-internet-contract
CREATE TABLE internet_contract (
    internet_contract_id     BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    internet_contract_number VARCHAR(50),
    risk_double              SMALLINT        DEFAULT 0,
    contract_id              BIGINT,
    manager_id               BIGINT,
    is_deliv                 SMALLINT,
    invoice_id               BIGINT,
    client_id                VARCHAR(16),
    int_contract_status_id   BIGINT,
    pdp                      VARCHAR(64),
    browser                  VARCHAR(500),
    product_id               VARCHAR(20),
    mdorder                  VARCHAR(150),
    payment_primary_rc       BIGINT,
    payment_secondary_rc     BIGINT,
    change_payment_date      TIMESTAMP,
    cancel_date              TIMESTAMP,
    total_sum_rur            NUMERIC(10, 2),
    total_rate               NUMERIC(25, 10),
    payment_dict_id          BIGINT,
    emoney_dict_id           VARCHAR(20),
    is_paid                  TIMESTAMP,
    platron_pg_order_id      VARCHAR(2000),
    platron_pg_payment_id    BIGINT,
    paid_amount              NUMERIC(10, 2),
    platron_is_refund        TIMESTAMP,
    platron_refund_amount    NUMERIC(10, 2),
    date_insert              TIMESTAMP       DEFAULT now(),
    statement_id             VARCHAR(255),
    user_identity_code_id    BIGINT,
    statement_file           TEXT,
    CONSTRAINT pk_internet_contract PRIMARY KEY (internet_contract_id)
);

--changeset internet-contract:001-indexes-internet-contract
CREATE INDEX idx_contract ON internet_contract (contract_id);
CREATE INDEX idx_deliv ON internet_contract (is_deliv);
CREATE INDEX idx_ic_number ON internet_contract (internet_contract_number);
CREATE INDEX idx_inet_contract_ak_invoice ON internet_contract (invoice_id);
CREATE UNIQUE INDEX idx_inet_contract_client_stmnt ON internet_contract (user_identity_code_id, statement_id);
CREATE INDEX idx_inet_contract_emoney_dict ON internet_contract (emoney_dict_id);
CREATE INDEX idx_inet_contract_payment_dict ON internet_contract (payment_dict_id);
CREATE INDEX idx_inet_contract_product ON internet_contract (product_id);
CREATE INDEX idx_inet_contract_status ON internet_contract (int_contract_status_id);
CREATE INDEX idx_inet_contract_subject ON internet_contract (manager_id);
CREATE INDEX idx_int_contr_date_in ON internet_contract (date_insert);
CREATE INDEX idx_is_paid ON internet_contract (is_paid);
CREATE INDEX idx_mdorder ON internet_contract (mdorder);
