--liquibase formatted sql

--changeset internet-contract:002-create-internet-contract-payment
CREATE TABLE internet_contract_payment (
    internet_contract_payment_id BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    internet_contract_id         BIGINT      NOT NULL,
    contract_id                  BIGINT      NOT NULL,
    mdorder                      VARCHAR(150),
    payment_primary_rc           BIGINT,
    payment_secondary_rc         BIGINT,
    date_request                 TIMESTAMP   DEFAULT now(),
    date_response                TIMESTAMP,
    paid_amount                  NUMERIC(10, 2) NOT NULL,
    payment_dict_id              BIGINT,
    CONSTRAINT pk_internet_contract_payment PRIMARY KEY (internet_contract_payment_id)
);

--changeset internet-contract:002-indexes-internet-contract-payment
CREATE UNIQUE INDEX udx_icp_contract_id_mdorder ON internet_contract_payment (contract_id, mdorder);
CREATE INDEX idx_icp_contract_id ON internet_contract_payment (contract_id);
CREATE INDEX idx_icp_internet_contract ON internet_contract_payment (internet_contract_id);
CREATE INDEX idx_icp_mdorder ON internet_contract_payment (mdorder);
