spring.application.name=partners-interaction
server.port=8080

# Logging
logging.level.root=info
logging.level.org.zalando.logbook=TRACE
logbook.predicate.exclude[0].path=/actuator/**
logging.level.org.springframework.ws=TRACE
ru.alfastrah.site.avto.ws.partners.interaction.logging.NormalizedFeignLogger=INFO

# Actuator
management.endpoints.web.exposure.include=health,prometheus
# Metrics
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=100ms,150ms,250ms,500ms,1s
management.metrics.enable.jvm=true

# Spring datasource UNICUS
spring.datasource.unicus.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.unicus.jdbc-url=jdbc:oracle:thin:@p750unicus.vesta.ru:1548:unc10g
spring.datasource.unicus.username=${UNICUS_DB_USERNAME}
spring.datasource.unicus.password=${UNICUS_DB_PASSWORD}
spring.datasource.unicus.maximumPoolSize=3
spring.datasource.unicus.minimumIdle=1

# PostgreSQL datasource
spring.datasource.postgres.driver-class-name=org.postgresql.Driver
spring.datasource.postgres.jdbc-url=jdbc:postgresql://adt-postgres-nginx.vesta.ru:5432/partners-interaction
spring.datasource.postgres.username=${POSTGRES_DB_USERNAME}
spring.datasource.postgres.password=${POSTGRES_DB_PASSWORD}
spring.datasource.postgres.maximumPoolSize=10
spring.datasource.postgres.minimumIdle=3

# ===============================
# Liquibase (configured via SpringLiquibase bean)
# ===============================
spring.liquibase.enabled=false

# ===============================
# Unicus Service
# ===============================
unicus.service.url=http://uniapp.vesta.ru:7788/unc10g