spring.application.name=internet-contract
app.version=@project.version@

# ===============================
# Embeded server
# ===============================
server.port=11004

# ===============================
# Spring actuator
# ===============================
management.endpoints.web.exposure.include=*

# ===============================
# Logging
# ===============================
logbook.exclude=/actuator/*
logging.level.org.zalando.logbook=TRACE
feign.client.config.default.loggerLevel=FULL

# ===============================
# Spring datasource UNICUS
# ===============================
spring.datasource.unicus.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.unicus.url=jdbc:oracle:thin:@p260unc4.vesta.ru:1566:uncunc
spring.datasource.unicus.username=${UNICUS_DB_USERNAME}
spring.datasource.unicus.password=${UNICUS_DB_PASSWORD}
spring.datasource.unicus.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.unicus.hikari.maximum-pool-size=50
spring.datasource.unicus.hikari.minimum-idle=3

# ===============================
# Spring datasource POSTGRES (internet_contract)
# ===============================
spring.datasource.postgres.driver-class-name=org.postgresql.Driver
spring.datasource.postgres.url=jdbc:postgresql://z14-4596-dpostg.vesta.ru:5432/internet-contract
spring.datasource.postgres.username=${POSTGRES_DB_USERNAME}
spring.datasource.postgres.password=${POSTGRES_DB_PASSWORD}
spring.datasource.postgres.hikari.connection-test-query=SELECT 1
spring.datasource.postgres.hikari.maximum-pool-size=20
spring.datasource.postgres.hikari.minimum-idle=3

# ===============================
# JPA (only postgres datasource)
# ===============================
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none

# ===============================
# Liquibase (only postgres datasource)
# ===============================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=internet_contract
