server.port=8080
spring.application.name=contract-signed

#Actuator
management.endpoint.health.enabled=true

#Common props
eosago.ok.double.mail.list=
notification.kasko.email.list=KatorginMI@alfastrah.ru
notification.general.email.list=KatorginMI@alfastrah.ru
use.altkraft.for.osago=true


#ActiveMQ
spring.activemq.broker-url=failover:(tcp://activemq:61616)?startupMaxReconnectAttempts=1&jms.redeliveryPolicy.maximumRedeliveries=3
spring.activemq.user=${ACTIVEMQ_LOGIN}
spring.activemq.password=${ACTIVEMQ_PASS}
spring.activemq.packages.trusted=ru.alfastrah.schemas.interplat4.send_contract_signed,java.math,java.lang

#SMTP
spring.mail.host=hpmail.vesta.ru
spring.mail.port=587
spring.mail.username=${SMTP_LOGIN}
spring.mail.password=${SMTP_PASS}
spring.mail.properties.mail.smtp.auth=true
mail.sender=epolicy

#PostgreSql
postgresql.datasource.jdbc-url=jdbc:postgresql://10.96.4.120:5432/contract-signed
postgresql.datasource.driver-class-name=org.postgresql.Driver
postgresql.datasource.username=${CONTRACT_SIGNED_DB_LOGIN}
postgresql.datasource.password=${CONTRACT_SIGNED_DB_PASS}
postgresql.datasource.pool-name="PostgresDb Pool"

postgresql.datasource.minimumIdle=1
postgresql.datasource.maximumPoolSize=10

#Liquibase
spring.liquibase.change-log=classpath:/liquibase/changelog/changelog-master.xml
spring.liquibase.url=jdbc:postgresql://10.96.4.120:5432/contract-signed
spring.liquibase.user=${CONTRACT_SIGNED_DB_LOGIN}
spring.liquibase.password=${CONTRACT_SIGNED_DB_PASS}
spring.liquibase.default-schema=public

#SQLServer
spring.mssql.url=jdbc:jtds:sqlserver://z14-3657-dbt.vesta.ru:1433/fuse_test
spring.mssql.username=${SQLSERVER_LOGIN}
spring.mssql.password=${SQLSERVER_PASS}
spring.mssql.driver=net.sourceforge.jtds.jdbc.Driver
spring.mssql.pool-name="SQLServer Pool"

#MyBatis
mybatis.mapper-locations=classpath*:/mybatis/*Mapper.xml
mybatis.type-handlers-package=ru.alfastrah.ws.contact.signed.mappers.typehandlers

#Outer Services
print-form.rest.service.url=http://ms-report:8010/report
print-form.soap.service.url=http://z14-1448-j8.vesta.ru:8181/cxf/PrintedFormsLocal
altcraft.rest.service.url=https://akd.alfastrahmail.ru:7443
cblogger.rest.service.url=http://cb-logs:8080/cxf/logCBEosago
cblogger.rest.service.authorization=${CB_LOGS_AUTH}
osago.replace.rest.service.url=http://ms-osago-replace:8480/osago-replace/partner/info
loyalty.rest.service.url=http://ms-loyalty:8190/loyalty
ms.references.rest.service.url=http://references-service:8086
mailing.url=http://ms-mailing:8045

#usb-hub
signature.hub.url=https://test-sign-adt.alfastrah.ru
signature.hub.login=${SIGNATURE_HUB_LOGIN}
signature.hub.password=${SIGNATURE_HUB_PASS}

contract-signed.rest.service.url=http://contract-signed:8080/

#unicus-starter
unicus.service.url=http://uncunc.vesta.ru:7788/uncunc
unicus.connection-timeout=60000
unicus.read-timeout=60000

#Bus-starter
bus.service.asContracts.url=http://ms-contract-info:8460/contract-info/cxf/AsContractsLocal

#logging.level.root=debug
logging.level.org.zalando.logbook=TRACE
logging.level.org.springframework.ws=TRACE
logging.level.ru.alfastrah.site.avto.ws.contact.signed.logging.NormalizedFeignLogger=INFO


spring.cloud.compatibility-verifier.enabled=false

altcraft.token=${ALTCRAFT_TOKEN}

party.ws.url=https://cdi.alfastrah.ru/cdi/soap/services/2_13/PartyWS
party.ws.username=${CDI_USERNAME}
party.ws.password=${CDI_PASSWORD}

ms.orange.rest.service.url=http://ms-orange:8160
spring.cloud.openfeign.client.config.msOrangeClient.connectTimeout=5000
spring.cloud.openfeign.client.config.msOrangeClient.readTimeout=5000
unicus-db-service.url=http://unicus-db-service:8080

#Swagger
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.url=/contract-signed/v3/api-docs
springdoc.swagger-ui.configUrl=/contract-signed/v3/api-docs/swagger-config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.doc-expansion=none
springdoc.cache.disabled=true
springdoc.swagger-ui.prefix=https://ms-adt-inner.vesta.ru/contract-signed