server.port=8080
spring.application.name=contract-signed

#Actuator
management.endpoints.web.exposure.include=health,prometheus
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=100ms,150ms,250ms,500ms,1s
management.metrics.enable.jvm=true

#Common props
eosago.ok.double.mail.list=
notification.kasko.email.list=KatorginMI@alfastrah.ru
notification.general.email.list=KatorginMI@alfastrah.ru
use.altkraft.for.osago=true

#ActiveMQ
#spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.broker-url=tcp://interplat4site.vesta.ru:61112
spring.activemq.user=${ACTIVEMQ_USERNAME}
spring.activemq.password=${ACTIVEMQ_PASSWORD}
spring.activemq.packages.trusted=ru.alfastrah.schemas.interplat4.send_contract_signed,java.math,java.lang

#SMTP
spring.mail.host=hpmail.vesta.ru
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
mail.sender=epolicy
#spring.mail.properties.mail.smtp.starttls.enable=true

#PostgreSql
postgresql.datasource.jdbc-url=jdbc:postgresql://10.96.4.120:5432/contract-signed
postgresql.datasource.driver-class-name=org.postgresql.Driver
postgresql.datasource.username=${CONTRACT_SIGNED_DB_LOGIN}
postgresql.datasource.password=${CONTRACT_SIGNED_DB_PASS}
postgresql.datasource.pool-name="PostgresDb Pool"

postgresql.datasource.minimumIdle=1
postgresql.datasource.maximumPoolSize=10

#Liquibase
spring.liquibase.change-log=classpath:/liquibase/changelog/changelog-master.xml
spring.liquibase.url=jdbc:postgresql://10.96.4.120:5432/contract-signed
spring.liquibase.user=${CONTRACT_SIGNED_DB_LOGIN}
spring.liquibase.password=${CONTRACT_SIGNED_DB_PASS}
spring.liquibase.default-schema=public

#SQLServer
spring.mssql.url=jdbc:jtds:sqlserver://z14-3657-dbt.vesta.ru:1433/fuse_test
spring.mssql.username=${FUSE_DB_USERNAME}
spring.mssql.password=${FUSE_DB_PASSWORD}
spring.mssql.driver=net.sourceforge.jtds.jdbc.Driver
spring.mssql.pool-name="SQLServer Pool"

#MyBatis
mybatis.mapper-locations=classpath*:/mybatis/*Mapper.xml
mybatis.type-handlers-package=ru.alfastrah.ws.contact.signed.mappers.typehandlers

#Outer Services
print-form.rest.service.url=http://ms-report:8010
altcraft.rest.service.url=https://akd.alfastrahmail.ru:7443
cblogger.rest.service.url=http://cb-logs.vesta.ru/cxf/logCBEosago
cblogger.rest.service.authorization=${CB_LOGS_AUTH}
osago.replace.rest.service.url=http://ms-adt-inner.vesta.ru/osago-replace/partner/info
loyalty.rest.service.url=http://ms-adt-inner.vesta.ru/loyalty
ms.references.rest.service.url=http://ms-adt-inner.vesta.ru/references-service
mailing.url=http://ms-adt-inner.vesta.ru

#usb-hub
signature.hub.url=https://test-sign-adt.alfastrah.ru
signature.hub.login=${SIGNATURE_HUB_LOGIN}
signature.hub.password=${SIGNATURE_HUB_PASS}


#contract-signed.rest.service.url=http://contract-signed.vesta.ru/
contract-signed.rest.service.url=http://localhost:8080/
#contract-signed.rest.service.url=http://z01-18849.dyn.vesta.ru:8080/

#unicus-starter
unicus.service.url=http://uncunc.vesta.ru:7788/uncunc
unicus.connection-timeout=60000
unicus.read-timeout=60000

#Bus-starter
bus.service.asContracts.url=http://ms-contract-info:8460/contract-info/cxf/AsContractsLocal

logging.level.root=info
logging.level.org.zalando.logbook=TRACE
logging.level.org.springframework.ws=TRACE
logging.level.ru.alfastrah.site.avto.ws.contact.signed.logging.NormalizedFeignLogger=INFO

spring.cloud.compatibility-verifier.enabled=false
management.health.mail.enabled=false

altcraft.token=${ALTCRAFT_TOKEN}

party.ws.url=https://cdi.alfastrah.ru/cdi/soap/services/2_13/PartyWS
party.ws.username=${CDI_USERNAME}
party.ws.password=${CDI_PASSWORD}

ms.orange.rest.service.url=http://ms-adt-inner.vesta.ru
spring.cloud.openfeign.client.config.msOrangeClient.connectTimeout=5000
spring.cloud.openfeign.client.config.msOrangeClient.readTimeout=5000
unicus-db-service.url=http://localhost:8081

#Swagger
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.doc-expansion=none
springdoc.cache.disabled=true
springdoc.swagger-ui.prefix=